### ISSUE TITLE
quick-xml

### ISSUE THREAD

**Issue by JeromeSchmied** [georust/gpx#106]
[`quick-xml`](https://crates.io/crates/quick-xml) is said to be a lot faster (about 50 times) than [`xml-rs`](https://crates.io/crates/xml-rs). Why not use that one instead?

**Comment by michaelkirk** [comment]
Care to open a PR with some benchmarks?On Jul 13, 2024, at 10:03, JeromeSchmied ***@***.***> wrote:﻿
quick-xml is said to be a lot faster (about 50 times) than xml-rs. Why not use that one instead?

**Comment by JeromeSchmied** [comment]
I'll see what I can do.

**Comment by JeromeSchmied** [comment]
Nah, it's too much I can't do it.
The whole `quick-xml` thing is just totally different, it's barely using anything else than `Cow`s, and therefore doesn't have `Iterator` implemented on stuff, that `xml-rs` has, for example.
