### ISSUE TITLE
Cannot get the real value of Time

### ISSUE THREAD

**Issue by petersohn** [georust/gpx#107]
Apparently, the only thing I can do with `Time` is to format it. I need the inner `OffsetDateTime`, for example to calculate durations. Currently the only way I can do it is to format it to a string then parse it because the underlying object is private. Is there a good reason for this?

**Comment by petersohn** [comment]
Why not just make the underlying `OffsetDateTime` public?

**Comment by lnicola** [comment]
It is, see https://docs.rs/gpx/latest/gpx/struct.Time.html#impl-From%3CTime%3E-for-OffsetDateTime.

**Comment by petersohn** [comment]
Oh, that works for me, thanks.

**Comment by lnicola** [comment]
The reason for this is to avoid exposing an implementation detail to the users, so we can change libraries more easily.
