### ISSUE TITLE
API to update creator attribute (feature)

### ISSUE THREAD

**Issue by enmagnus** [georust/gpx#40]
Strava uses the creator attribute in GPX files in a very special way. Not being able to set it when creating a GPX file will prevent Strava from using elevation data when uploading the GPX file there. 

From the Strava API docs in https://developers.strava.com/docs/uploads/

> Device type is detected in all file types from standard ‘creator’ tags. These tags are then matched to a list of known devices. In some cases the name of the device will be displayed along with the activity details on strava.com.
> 
> A generic “with barometer” device is provided to force the system to use the elevation data from TCX and GPX file types. One only needs to add “with barometer” to the end of the creator name. 

I suggest having a way to programmatically change the creator attribute from "https://github.com/georust/gpx".

**Comment by oherrala** [comment]
Hi @enmagnus

Does the PR #41 solve your problem? Can you test it?

**Comment by enmagnus** [comment]
Tested in my context and works just as needed. Great!
