### ISSUE TITLE
Cannot parse <copyright> tag in metadata

### ISSUE THREAD

**Issue by pelmers** [georust/gpx#45]
The GPX 1.1 spec defines a  [copyright type](http://www.topografix.com/GPX/1/1/#type_copyrightType) which may be in the metadata tag. In gpx v0.8 parsing such a file returns `Error(InvalidChildElement("copyright", "metadata"), ...)`.

Metadata:
```
<copyright> copyrightType </copyright> [0..1]
```

copyrightType:
```
<copyright
  author="xsd:string [1] ?">
    <year> xsd:gYear </year> [0..1] ?
    <license> xsd:anyURI </license> [0..1] ?
</copyright>
```

For my purposes I wouldn't mind if the parser just skips this element and ignores it as long as the file can be parsed.

**Comment by urschrei** [comment]
Closed in #46
