### ISSUE TITLE
Panic for tracks with empty name

### ISSUE THREAD

**Issue by soruh** [georust/gpx#54]
When opening a file with this format:
```xml
<gpx>
    <!--- metadata --->
    <trk>
        <name></name>
        <!--- rest of track data --->
    </trk>
</gpx>
```

`gpx` panics with the message: `no content inside string`.

Is there a reason `string::consume` is called with `allow_empty=false` [here](https://github.com/georust/gpx/blob/master/src/parser/track.rs#L32)?
Is this construct just invalid and the App I used has generated an invalid `gpx` file?
If that is the case, since all other gpx applications I tested don't have a problem with this, would it make sense to accept this anyways?

**Comment by urschrei** [comment]
If I'm reading it correctly, It looks like empty track names are allowed by the [spec](https://www.topografix.com/GPX/1/1/#type_trkType), but the crate changed this in https://github.com/georust/gpx/commit/840781eff8f0399c8fe8e6534d2720167a103773. @dhontecillas you made the change – what do you think about loosening the restriction?

**Comment by soruh** [comment]
It looks to me like that commit didn't explicitly disable empty names but added the `allow_empty` parameter and left its value for the fields not mentioned in the commit message ("desc", "cmt", "description", "keywords", "src" ) to false (the way it worked before the commit) so the decision to handle empty names this way wasn't made there. (If dhontecillas _does_ have insight on this, that'd be great of course.)

I think it would make sense to allow this since other applications do and rely on it and I don't really see any downside.

**Comment by soruh** [comment]
(It looks to me like this logic has been present since [the initial commit](https://github.com/georust/gpx/commit/67ca09b98e980cb042762b2db431aaa2bd2a9d51#diff-8d027b731e6c8b3a31918ca23efb56107738b4be8da40f79cba43d83b0f8910dR31).)

**Comment by brendanashworth** [comment]
> I think it would make sense to allow this since other applications do and rely on it and I don't really see any downside.

I agree. Do you want to make a pull request changing this, with a test?

> (It looks to me like this logic has been present since the initial commit.)

😅

**Comment by urschrei** [comment]
> (It looks to me like this logic has been present since [the initial commit](https://github.com/georust/gpx/commit/67ca09b98e980cb042762b2db431aaa2bd2a9d51#diff-8d027b731e6c8b3a31918ca23efb56107738b4be8da40f79cba43d83b0f8910dR31).)

Oops. Sorry!

**Comment by soruh** [comment]
> Do you want to make a pull request changing this, with a test?
Sure, I'll get started on that right now.

**Comment by urschrei** [comment]
Published to crates.io as 0.8.3

**Comment by soruh** [comment]
Ah, great. Thank you!
