### ISSUE TITLE
Implementing serde (De)Serialize for GPX structs?

### ISSUE THREAD

**Issue by mkroehnert** [georust/gpx#59]
Hello all,
first of all I want to say thank you for your work on the GPX crate.

I am using this crate for a hobby project which allows recording GPS tracks via the webbrowser GPS API and exporting them as GPX. See https://gitlab.com/mkroehnert/trailcorder.

In addition to the existing XML export option, I am currently testing a feature for persisting the recorded data in local storage as JSON objects, which requires deriving serde (De)Serialize for the structs in this crate.

Since it is not easily possible to add serde #derive to structs that are not part of my own crate, I added the required changes in the following commit of my fork: https://github.com/mkroehnert/gpx/commit/26a0b8b1bd9c6348a86c9a30ccff2b963245a05f

Before putting more work into hiding the serde dependency behind a feature flag, 
I wanted to ask if this is a contribution you would consider adding/merging,

**Comment by urschrei** [comment]
Hi @mkroehnert, yes of course. As you say, a feature flag would be the preferred way to implement this. Just out of curiosity, is the JSON actually GeoJSON, and if not, is there a reason for that? I ask because if it _is_ GeoJSON, then perhaps an approach that leverages [geozero](https://github.com/georust/geozero) might be better.

**Comment by mkroehnert** [comment]
Thanks for the response @urschrei .
Currently it is just the data structure serialized to plain JSON.
So far, I Did not check on GeoJSON but it might be good idea look into it. Thanks for the pointer.

**Comment by mkroehnert** [comment]
If someone is interested, I am using the gpx crate in the following prototype, where I am testing different things related to WASM and GPS in the browser.
https://gitlab.com/mkroehnert/trailcorder
