### ISSUE TITLE
Parsing fails on extensions

### ISSUE THREAD

**Issue by supersnellehenk** [georust/gpx#89]
Hi,

I've got a GPX file coming from QMapShack with extensions that fails to parse, found here: https://pastebin.com/ETVKuhrZ.
I'd expect to at least get a GPX result without extensions, since the library doesn't support them.

GPX library version: 0.9.0
Backtrace if interesting: https://pastebin.com/MKGNt68H

**Comment by lnicola** [comment]
Can you attach the file and paste the backtrace here? pastebin.com is throwing a fit.

**Comment by supersnellehenk** [comment]
[A12 Veenendaal Wageningen.txt](https://github.com/georust/gpx/files/11651416/A12.Veenendaal.Wageningen.txt)
[backtrace.txt](https://github.com/georust/gpx/files/11651422/backtrace.txt)
Had to rename it, Github doesn't support GPX files ;)
Thanks for taking a look @lnicola

**Comment by lnicola** [comment]
Looking at the tests (I've never seen a GPX until now :sweat_smile:), we support extensions under `<metadata>`, `<trk>` and `<rte>`, but yours are on the root. Perhaps we don't accept them in that position.

**Comment by supersnellehenk** [comment]
> Looking at the tests (I've never seen a GPX until now 😅), we support extensions under `<metadata>`, `<trk>` and `<rte>`, but yours are on the root. Perhaps we don't accept them in that position.

I removed the extensions section on L475-481 from my file and it loads fine. Seems like the library should support this?

**Comment by lnicola** [comment]
Something like #90 should fix it, but I don't feel comfortable merging it without a review.

**Comment by supersnellehenk** [comment]
> Something like #90 should fix it, but I don't feel comfortable merging it without a review.

Thanks for the PR, I'll await the release so we can use the files from QMapStack without manually editing them. <3

**Comment by lnicola** [comment]
You can use a [git dependency](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories) on my branch in the meanwhile.

**Comment by supersnellehenk** [comment]
> You can use a [git dependency](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories) on my branch in the meanwhile.

Thanks, didn't know that existed (Rust noob). Works wonders!
